"""Market-pulse summary — an at-a-glance read over the whole feed.

Two parts, deliberately split by cost:

  - **Aggregates** (model-free, recomputed every tick): a net directional bias
    per category and overall, weighted by priority × confidence, plus the most
    important individual hypotheses. These drive the graphics.
  - **Narrative** (German, 3-4 sentences): generated by the throttled LLM batch
    (:mod:`news.llm_workflow`) and cached in the store, with a model-free template
    fallback so the panel is never empty. Refreshed once per LLM cycle (~3 min).
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone

from .models import PRIORITY_RANK, ImpactDirection, NewsItem

_SIGN = {ImpactDirection.BULLISH: 1.0, ImpactDirection.BEARISH: -1.0, ImpactDirection.NEUTRAL: 0.0}

_LABEL_EN = [
    (0.5, "strong bullish"), (0.15, "bullish"), (-0.15, "neutral"),
    (-0.5, "bearish"), (-1.1, "strong bearish"),
]
_LABEL_DE = {
    "strong bullish": "stark bullisch", "bullish": "bullisch", "neutral": "neutral",
    "bearish": "bärisch", "strong bearish": "stark bärisch",
}
LOOKBACK_HOURS = 48.0


def _label(score: float) -> str:
    for thr, lab in _LABEL_EN:
        if score >= thr:
            return lab
    return "strong bearish"


def _weight(item: NewsItem) -> float:
    h = item.hypothesis
    return PRIORITY_RANK.get(item.priority.value, 0) * (h.confidence if h else 0.0)


def _bias(items: list[NewsItem]) -> dict:
    sw = sum(_weight(i) for i in items)
    score = 0.0 if sw == 0 else sum(_SIGN[i.hypothesis.direction] * _weight(i) for i in items) / sw
    dirs = [i.hypothesis.direction for i in items]
    return {
        "score": round(score, 3),
        "label": _label(score),
        "label_de": _LABEL_DE[_label(score)],
        "n": len(items),
        "bullish": dirs.count(ImpactDirection.BULLISH),
        "bearish": dirs.count(ImpactDirection.BEARISH),
        "neutral": dirs.count(ImpactDirection.NEUTRAL),
    }


def compute_aggregates(items: list[NewsItem], lookback_hours: float = LOOKBACK_HOURS) -> dict:
    """Net directional bias overall + per category, and the top hypotheses."""
    now = datetime.now(timezone.utc)
    rel = []
    for it in items:
        if it.hypothesis is None:
            continue
        ts = it.timestamp if it.timestamp.tzinfo else it.timestamp.replace(tzinfo=timezone.utc)
        if (now - ts).total_seconds() / 3600.0 <= lookback_hours:
            rel.append(it)

    cats: dict[str, list[NewsItem]] = {}
    for it in rel:
        cats.setdefault(it.category.value, []).append(it)
    categories = [{"category": c, **_bias(v)} for c, v in cats.items()]
    categories.sort(key=lambda d: abs(d["score"]), reverse=True)

    top = sorted(rel, key=lambda i: (_weight(i), i.timestamp), reverse=True)[:6]
    top_payload = [{
        "id": it.id,
        "title": it.title,
        "category": it.category.value,
        "priority": it.priority.value,
        "direction": it.hypothesis.direction.value,
        "asset": it.hypothesis.asset,
        "confidence": it.hypothesis.confidence,
        "status": it.hypothesis.status.value,
        "provisional_status": it.hypothesis.provisional_status,
        "provisional_return": it.hypothesis.provisional_return,
    } for it in top]

    return {"overall": _bias(rel), "categories": categories, "top": top_payload,
            "lookback_hours": lookback_hours}


# ── narrative (German 3-4 sentences) ─────────────────────────────────────────
SYSTEM_PROMPT = (
    "Du bist ein Markt-Stratege. Fasse die aktuelle Marktlage auf Deutsch in 3 bis 4 "
    "prägnanten Sätzen zusammen — was gerade wichtig ist und wie der Tenor (bullisch/"
    "bärisch) je Anlageklasse ist. Antworte mit NUR einem JSON-Objekt."
)


def _build_prompt(agg: dict, top: list[dict]) -> str:
    cats = "; ".join(f"{c['category']}: {c['label']} ({c['score']:+.2f}, n={c['n']})"
                     for c in agg["categories"]) or "keine Daten"
    heads = "\n".join(f"- [{t['category']}/{t['priority']}] {t['direction']} {t['asset']}: {t['title']}"
                      for t in top) or "keine"
    o = agg["overall"]
    return (
        f"Gesamt-Tenor: {o['label']} (Score {o['score']:+.2f}, {o['bullish']} bullisch / "
        f"{o['bearish']} bärisch / {o['neutral']} neutral).\n"
        f"Bias je Kategorie: {cats}\n\n"
        f"Wichtigste Schlagzeilen:\n{heads}\n\n"
        'Gib JSON zurück: { "narrative": "<3-4 Sätze auf Deutsch>" }'
    )


def _heuristic_narrative(agg: dict, top: list[dict]) -> str:
    o = agg["overall"]
    if o["n"] == 0:
        return "Aktuell liegen keine ausgewerteten Nachrichten vor. Sobald der Feed lädt, erscheint hier eine Einschätzung der Marktlage."
    lead_cat = agg["categories"][0] if agg["categories"] else None
    top_head = top[0]["title"] if top else ""
    parts = [
        f"Der Gesamttenor der News ist aktuell {o['label_de']} "
        f"({o['bullish']} bullische, {o['bearish']} bärische Signale bei {o['n']} ausgewerteten Meldungen)."
    ]
    if lead_cat:
        parts.append(
            f"Am deutlichsten ist die Tendenz im Bereich {lead_cat['category']} "
            f"({lead_cat['label_de']}, Score {lead_cat['score']:+.2f})."
        )
    if top_head:
        parts.append(f"Im Fokus steht: „{top_head}“.")
    parts.append("Die Einschätzung aktualisiert sich laufend mit neuen Schlagzeilen.")
    return " ".join(parts)


def _parse_json(text: str) -> dict | None:
    m = re.search(r"\{.*\}", text or "", re.DOTALL)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except json.JSONDecodeError:
        return None


def generate_narrative(agg: dict, top: list[dict], backend=None) -> tuple[str, str]:
    """(text, model) — LLM German summary if available, else template."""
    if backend is not None and getattr(backend, "name", "") not in ("", "mock"):
        try:
            raw = backend.generate(_build_prompt(agg, top), system=SYSTEM_PROMPT,
                                   max_tokens=400, temperature=0.3)
            data = _parse_json(raw or "")
            if data and data.get("narrative"):
                return str(data["narrative"]).strip()[:900], getattr(backend, "name", "llm")
        except Exception:  # noqa: BLE001
            pass
    return _heuristic_narrative(agg, top), "heuristic"


def refresh_narrative(store, backend=None) -> dict:
    """Recompute aggregates + (re)generate the narrative, persist, and return it.

    Called by the throttled LLM workflow so the German text refreshes once per cycle.
    """
    agg = compute_aggregates(store.all_items())
    text, model = generate_narrative(agg, agg["top"], backend=backend)
    payload = {"narrative": text, "narrative_model": model,
               "narrative_at": datetime.now(timezone.utc).isoformat()}
    store.set_market(payload)
    return payload


def snapshot(store) -> dict:
    """Fresh aggregates (model-free) + the cached narrative (heuristic until the
    LLM cycle fills it). Cheap enough to run on every tick."""
    agg = compute_aggregates(store.all_items())
    cached = store.get_market()
    if cached.get("narrative"):
        narrative = cached["narrative"]
        model = cached.get("narrative_model", "heuristic")
        at = cached.get("narrative_at")
    else:
        narrative, model = generate_narrative(agg, agg["top"], backend=None)
        at = datetime.now(timezone.utc).isoformat()
    return {**agg, "narrative": narrative, "narrative_model": model, "narrative_at": at}
